name: QR Forge
description: High-quality QR code generator with SVG and PNG support, featuring both CLI and GUI interfaces
topics:
  - qr-code
  - qr-generator  
  - svg
  - png
  - rust
  - cli
  - gui
  - macos
  - cross-platform
  - developer-tools
  - code-generator
  - desktop-app
homepage: https://github.com/fra2404/qr-forge
license: MIT
