name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  actions: read
  deployments: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build Release (macOS only)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Verify icon exists
        run: |
          if [ -f "image.png" ]; then
            echo "✅ Found existing image.png icon"
            ls -la image.png
          else
            echo "❌ image.png not found!"
            exit 1
          fi

      - name: Build QR Forge (CLI + GUI + App)
        run: |
          chmod +x build_app.sh create_icon.sh
          ./build_app.sh

      - name: Debug build structure
        run: |
          echo "=== Build directory structure ==="
          find build -type f -name "*" | head -20
          echo ""
          echo "=== Apps directory ==="
          ls -la build/apps/ || echo "apps directory not found"
          echo ""
          echo "=== CLI directory ==="
          ls -la build/cli/ || echo "cli directory not found"

      - name: Create macOS DMG
        run: |
          if [ -d "build/apps/QR Forge.app" ]; then
            echo "Creating DMG from build/apps/QR Forge.app"
            hdiutil create -volname "QR Forge" -srcfolder "build/apps/QR Forge.app" -ov -format UDZO QR-Forge-GUI-macos.dmg
          else
            echo "App bundle not found at build/apps/QR Forge.app"
            echo "Looking for alternative locations..."
            find . -name "QR Forge.app" -type d
            exit 1
          fi

      - name: Create CLI archive
        run: |
          if [ -d "build/cli" ] && [ -f "build/cli/qr-forge" ]; then
            echo "Creating CLI archive from build/cli"
            cd build/cli
            tar -czf ../../qr-forge-cli-macos.tar.gz qr-forge qr-forge-gui ../../README.md ../../LICENSE
          else
            echo "CLI binaries not found in build/cli"
            echo "Looking for CLI binaries..."
            find . -name "qr-forge" -type f
            exit 1
          fi

      - name: Verify build artifacts
        run: |
          echo "=== Checking build artifacts ==="
          if [ -f "QR-Forge-GUI-macos.dmg" ]; then
            echo "✅ DMG created successfully:"
            ls -la QR-Forge-GUI-macos.dmg
          else
            echo "❌ DMG not found"
          fi
          
          if [ -f "qr-forge-cli-macos.tar.gz" ]; then
            echo "✅ CLI archive created successfully:"
            ls -la qr-forge-cli-macos.tar.gz
          else
            echo "❌ CLI archive not found"
          fi
          
          echo ""
          echo "=== Root directory contents ==="
          ls -la

      - name: Release
        uses: softprops/action-gh-release@v1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: QR Forge ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## 🔥 QR Forge ${{ github.ref_name }} - macOS Release

            Professional QR code generator with multiple formats and interfaces.

            ### ✨ Features
            - CLI QR code generator with multiple output formats
            - GUI application with real-time preview  
            - Support for PNG, SVG, JPEG formats
            - Customizable colors and sizes
            - Native macOS app bundle with custom icon

            ### 📦 Downloads

            **🍎 macOS Users:**
            - **QR-Forge-GUI-macos.dmg** - Complete GUI app (drag to Applications)
            - **qr-forge-cli-macos.tar.gz** - CLI tools (terminal use)

            ### 🚀 Quick Start
            - **GUI**: Mount the DMG and drag QR Forge to Applications
            - **CLI**: Extract and run `./qr-forge "Your text here" -o output.svg`

            See [README.md](https://github.com/fra2404/qr-forge#readme) for detailed usage instructions.

            ---
            *Cross-platform builds (Linux/Windows) coming soon!*
          files: |
            QR-Forge-GUI-macos.dmg
            qr-forge-cli-macos.tar.gz
