name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build Release (macOS only)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Generate QR Forge icon
        run: |
          chmod +x generate_icon.py
          python3 generate_icon.py

      - name: Build QR Forge (CLI + GUI + App)
        run: |
          chmod +x build_app.sh create_icon.sh
          ./build_app.sh

      - name: Create macOS DMG
        run: |
          # Create DMG from the organized build location
          hdiutil create -volname "QR Forge" -srcfolder "build/apps/QR Forge.app" -ov -format UDZO QR-Forge-GUI-macos.dmg

      - name: Create CLI archive
        run: |
          cd build/cli
          tar -czf ../../qr-forge-cli-macos.tar.gz qr-forge qr-forge-gui ../../README.md ../../LICENSE

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: QR Forge ${{ github.ref_name }}
          body: |
            ## 🔥 QR Forge ${{ github.ref_name }} - macOS Release

            Professional QR code generator with multiple formats and interfaces.

            ### ✨ Features
            - CLI QR code generator with multiple output formats
            - GUI application with real-time preview  
            - Support for PNG, SVG, JPEG formats
            - Customizable colors and sizes
            - Native macOS app bundle with custom icon

            ### 📦 Downloads

            **🍎 macOS Users:**
            - **QR-Forge-GUI-macos.dmg** - Complete GUI app (drag to Applications)
            - **qr-forge-cli-macos.tar.gz** - CLI tools (terminal use)

            ### 🚀 Quick Start
            - **GUI**: Mount the DMG and drag QR Forge to Applications
            - **CLI**: Extract and run `./qr-forge "Your text here" -o output.svg`

            See [README.md](https://github.com/fra2404/qr-forge#readme) for detailed usage instructions.

            ---
            *Cross-platform builds (Linux/Windows) coming soon!*
          files: |
            QR-Forge-GUI-macos.dmg
            qr-forge-cli-macos.tar.gz
